name: flutterbuyandsell
description: Your Local Market Place.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2
publish_to: none

# CCV 3.5 = 3.5.0+35
# CCV 3.3 = 3.4.0+2834
# CCV 3.3 = 3.3.0+28
# CCV 3.2 = 3.2.0+27
# CCV 3.1 = 3.1.0+26
# CCV 3.0 = 3.0.0+25
# CCV 2.9 = 2.9.0+24
# CCV 2.8 = 2.8.0+23
# CCV 2.7 = 2.7.0+22
# CCV 2.6 = 2.6.0+21
# CCV 2.5 = 2.5.0+20
# CCV 2.4 = 2.4.0+19
# CCV 2.3 = 2.3.0+18
# CCV 2.3 = 2.3.0+17
# CCV 2.2 = 2.2.0+16
# CCV 2.2 = 2.2.0+15
# CCV 2.1 = 2.1.0+14
# CCV 2.0 = 2.0.0+13
# CCV 1.9 = 1.9.0+12
# CCV 1.8 = 1.8.0+11
# CCV 1.7 = 1.7.0+10
# CCV 1.6 = 1.6.0+9
# CCV 1.5 = 1.5.0+7
# CCV 1.4 = 1.4.0+6
# CCV 1.4 = 1.4.0+5
# CCV 1.3 = 1.3.0+4
# CCV 1.2 = 1.2.0+3
# CCV 1.1 = 1.1.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: 2.0.15 
  http: 0.13.5
  provider: 6.0.3
  connectivity: 3.0.6
  # connectivity_plus: 2.3.6

  
  theme_manager: ^1.1.0
  flutter_map: 2.2.0
  cached_network_image: 3.2.1
  # multi_image_picker: 4.8.1 
  reactive_multi_image_picker: 0.7.0
  easy_localization: 3.0.1
  #latlng: 0.1.0
  latlong2: 0.8.1
  # flutter_map_tappable_polyline: 3.2.0
  # image_picker: ^0.8.5+3
  # flutter_widget_from_html: 0.8.1+1
  flutter_html: 2.2.1
  sembast: 3.2.0+1
  path_provider: 2.0.11
  intl: 0.17.0
  shimmer: 2.0.0
  url_launcher: 6.1.5
  carousel_slider: 4.1.1

  firebase_core: 1.20.1
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: 11.0.0
  firebase_database: 7.2.1
  firebase_auth: 3.11.2
  #flutter_native_admob: 2.1.0+3 ###
  google_mobile_ads: 2.0.1
  # google_mobile_ads : 
  #   git:
  #     url: https://github.com/SuaMusica/googleads-mobile-flutter.git
  #     path: packages/google_mobile_ads
  #     ref: feature/suamusica
  google_sign_in: 5.4.1
  flutter_facebook_auth: 3.5.6
  photo_view: 0.14.0 
  progress_dialog_null_safe: 1.0.7
  flutter_braintree: 3.0.0 #//2.3.1
  # launch_review: 3.0.1
  # package_info: 2.0.2
  package_info_plus: 1.4.3
  fluttericon: 2.0.0 
  flutter_stripe: 4.0.0
  flutter_credit_card: 3.0.3
  fluttertoast: 8.0.9
  permission_handler: 10.0.0
  permission_handler_platform_interface: 3.7.0
  geolocator: 9.0.1  # Sticked with 7.6.2 for now. If app support android 12, need to update this lib
  # share: 2.0.4
  share_plus: 4.0.10+1
  the_apple_sign_in: 1.1.1
  razorpay_flutter: 1.3.2
  group_radio_button: 1.2.0
  flutter_native_image: 0.0.6+1
  # flutter_paystack: 1.0.5+1
  firebase_dynamic_links: 4.3.4
  in_app_purchase: 3.0.8 
  # camera: 0.8.0
  # flutter_better_camera: 1.0.2+1
  flutter_linkify: 5.0.2
  google_maps_flutter: 2.1.12 
  flutter_datetime_picker: 
    path : packages/flutter_datetime_picker
  collection: 1.16.0
  file_picker: 5.0.1
  # video_thumbnail: 0.5.2
  video_thumbnail:
    git: https://github.com/ajbcoder/video_thumbnail
  video_player: 2.2.7 
  flutter_svg: 0.23.0+1
  community_material_icon: 5.9.55
  visibility_detector: 0.3.3
  geocoding: 2.0.4
  camera: 0.10.5
  app_tracking_transparency: 2.0.2+4 
  firebase_crashlytics: ^2.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   xml: '6.1.0'
 
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder_circle_image.png
   - assets/images/placeholder_image.png
   - assets/langs/en-US.json
   - assets/langs/hi-IN.json
   - assets/langs/en-IN.json
   
   - assets/images/verify_email_icon.jpg
   - assets/images/down.png
   - assets/images/baesline_access_time_black_24.png
   - assets/images/baseline_check_green_24.png
   - assets/images/baseline_graph_black_24.png
   - assets/images/baseline_price_down_black_24.png
   - assets/images/chat.png
   - assets/images/seo.png
   - assets/images/upload.png
   - assets/images/baseline_price_up_black_24.png
   - assets/images/baseline_empty_item_grey_24.png
   - assets/images/home_icon/discount_products.png
   - assets/images/home_icon/easy_payment.png
   - assets/images/home_icon/featured_products.png
   - assets/images/home_icon/free_download.png
   - assets/images/trending.png
   - assets/images/flutter_buy_and_sell_logo.png
   - assets/images/flutter_buy_and_sell_logo_light.png
   - assets/images/baseline_pin_black_24.png
   - assets/images/baseline_favourite_grey_24.png
   - assets/images/default_image.png
   - assets/images/baseline_promotion_color_74.png
   - assets/images/user_default_photo.png
   - assets/images/loaction_illustration.svg
   - assets/images/slider_1.svg
   - assets/images/slider_2.svg
   - assets/images/slider_3.svg
   - assets/images/demo_alert.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
